---
- name: update web servers
  hosts: web
  become: yes
  tasks:
  - name: ensure selinux is permissive
    ansible.posix.selinux:
      policy: targeted
      state: permissive
        
  - name: ensure httpd conf is updated
    copy:
      src: httpd.conf
      dest: /etc/httpd/conf/httpd.conf

  - name: ensure httpd is restarted
    service:
      name: httpd
      state: restarted

...      
