---
- name: update web servers
  hosts: ubuntu
  become: yes

  tasks:
  - name: ensure apache is present
    package:
      name: apache2 
      state: present
  - name: ensure apache is started 
    service:
      name: apache2
      state: started
  - name: ensure apache is enable
    service:
      name: apache2
      enabled: yes

...      
