---
- name: update ubuntu servers
  hosts: ubuntu
  become: yes

  tasks:
  - name: ensure apache is present
    package:
      name: apache2 
      state: present
  - name: ensure apache is started 
    service:
      name: apache2
      state: started
  - name: ensure apache is enable
    service:
      name: apache2
      enabled: yes

- name: update ec2 servers
  hosts: ec2user
  become: yes

  tasks:
  - name: ensure apache is present
    package:
      name: httpd
      state: present
  - name: ensure apache is started 
    service:
      name: httpd
      state: started
  - name: ensure apache is enable
    service:
      name: httpd
      enabled: yes

...      
